import {React, useEffect} from 'react';
import { Redirect } from 'react-router-dom';
import '../css/List.css';

const List = (props) => {
    const [user, setUser] = [props.user, props.setUser];
    useEffect(() => {
        if(user) {
            document.title = `${user.username}'s List`;
        }
        else {
            document.title = `Your List`;
        }
    }, [user]);

    /* ----------------------------------- jsx ---------------------------------- */
    if(user) {
        return (
            <div>
                <div id="main-header">
                    <div className="left">
                        <h1 className="rainbow" id="title">
                            Showstop
                        </h1>
                    </div>
                    <div className="middle">
                        <h2 id="list-name">{user.username}'s List</h2>
                    </div>
                    <div className="right">
                        <input type="button" value="Add Entry"/>
                    </div>
                </div>
                <table>
                    <thead>
                        <tr id="status-header">
                            <th>Everything</th>
                            <th>Watching</th>
                            <th>Completed</th>
                            <th>On Hold</th>
                            <th>Dropped</th>
                            <th>Plan to Watch</th>
                            <th id="search-button">&#128269;</th>
                        </tr>
                    </thead>
                    <thead>
                        <tr className="sticky" id="info-header">
                            <th>#</th>
                            <th>Title</th>
                            <th>Rating</th>
                            <th>Type</th>
                            <th>Status</th>
                            <th>Progress</th>
                            <th>Tags</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Lorem.</td>
                            <td>Ullam.</td>
                            <td>Vel.</td>
                            <td>At.</td>
                            <td>Quis.</td>
                        </tr>
                        <tr>
                        <td>Quas!</td>
                        <td>Velit.</td>
                        <td>Quisquam?</td>
                        <td>Rerum?</td>
                        <td>Iusto?</td>
                        </tr>
                        <tr>
                        <td>Voluptates!</td>
                        <td>Fugiat?</td>
                        <td>Alias.</td>
                        <td>Doloribus.</td>
                        <td>Veritatis.</td>
                        </tr>
                        <tr>
                        <td>Maiores.</td>
                        <td>Ab.</td>
                        <td>Accusantium.</td>
                        <td>Ullam!</td>
                        <td>Eveniet.</td>
                        </tr>
                        <tr>
                        <td>Hic.</td>
                        <td>Id!</td>
                        <td>Officiis.</td>
                        <td>Modi!</td>
                        <td>Obcaecati.</td>
                        </tr>
                        <tr>
                        <td>Soluta.</td>
                        <td>Ad!</td>
                        <td>Impedit.</td>
                        <td>Alias!</td>
                        <td>Ad.</td>
                        </tr>
                        <tr>
                        <td>Expedita.</td>
                        <td>Quo.</td>
                        <td>Exercitationem!</td>
                        <td>Optio?</td>
                        <td>Ipsum?</td>
                        </tr>
                        <tr>
                        <td>Commodi!</td>
                        <td>Rem.</td>
                        <td>Aspernatur.</td>
                        <td>Accusantium!</td>
                        <td>Maiores.</td>
                        </tr>
                        <tr>
                        <td>Omnis.</td>
                        <td>Cumque?</td>
                        <td>Eveniet!</td>
                        <td>Mollitia?</td>
                        <td>Vero.</td>
                        </tr>
                        <tr>
                        <td>Error!</td>
                        <td>Inventore.</td>
                        <td>Quasi!</td>
                        <td>Ducimus.</td>
                        <td>Repudiandae!</td>
                        </tr>
                        <tr>
                        <td>Dolores!</td>
                        <td>Necessitatibus.</td>
                        <td>Corrupti!</td>
                        <td>Eum.</td>
                        <td>Sunt!</td>
                        </tr>
                        <tr>
                        <td>Ea.</td>
                        <td>Culpa?</td>
                        <td>Quam?</td>
                        <td>Nemo!</td>
                        <td>Sit!</td>
                        </tr>
                        <tr>
                        <td>Veritatis!</td>
                        <td>Facilis.</td>
                        <td>Expedita?</td>
                        <td>Ipsam!</td>
                        <td>Omnis!</td>
                        </tr>
                        <tr>
                        <td>Vitae.</td>
                        <td>Cumque.</td>
                        <td>Repudiandae.</td>
                        <td>Ut?</td>
                        <td>Sed!</td>
                        </tr>
                        <tr>
                        <td>Accusantium.</td>
                        <td>Adipisci.</td>
                        <td>Sit.</td>
                        <td>Maxime.</td>
                        <td>Harum.</td>
                        </tr>
                        <tr>
                        <td>Quas!</td>
                        <td>Velit.</td>
                        <td>Quisquam?</td>
                        <td>Rerum?</td>
                        <td>Iusto?</td>
                        </tr>
                        <tr>
                        <td>Voluptates!</td>
                        <td>Fugiat?</td>
                        <td>Alias.</td>
                        <td>Doloribus.</td>
                        <td>Veritatis.</td>
                        </tr>
                        <tr>
                        <td>Maiores.</td>
                        <td>Ab.</td>
                        <td>Accusantium.</td>
                        <td>Ullam!</td>
                        <td>Eveniet.</td>
                        </tr>
                        <tr>
                        <td>Hic.</td>
                        <td>Id!</td>
                        <td>Officiis.</td>
                        <td>Modi!</td>
                        <td>Obcaecati.</td>
                        </tr>
                        <tr>
                        <td>Soluta.</td>
                        <td>Ad!</td>
                        <td>Impedit.</td>
                        <td>Alias!</td>
                        <td>Ad.</td>
                        </tr>
                        <tr>
                        <td>Expedita.</td>
                        <td>Quo.</td>
                        <td>Exercitationem!</td>
                        <td>Optio?</td>
                        <td>Ipsum?</td>
                        </tr>
                        <tr>
                        <td>Commodi!</td>
                        <td>Rem.</td>
                        <td>Aspernatur.</td>
                        <td>Accusantium!</td>
                        <td>Maiores.</td>
                        </tr>
                        <tr>
                        <td>Omnis.</td>
                        <td>Cumque?</td>
                        <td>Eveniet!</td>
                        <td>Mollitia?</td>
                        <td>Vero.</td>
                        </tr>
                        <tr>
                        <td>Error!</td>
                        <td>Inventore.</td>
                        <td>Quasi!</td>
                        <td>Ducimus.</td>
                        <td>Repudiandae!</td>
                        </tr>
                        <tr>
                        <td>Dolores!</td>
                        <td>Necessitatibus.</td>
                        <td>Corrupti!</td>
                        <td>Eum.</td>
                        <td>Sunt!</td>
                        </tr>
                        <tr>
                        <td>Ea.</td>
                        <td>Culpa?</td>
                        <td>Quam?</td>
                        <td>Nemo!</td>
                        <td>Sit!</td>
                        </tr>
                        <tr>
                        <td>Veritatis!</td>
                        <td>Facilis.</td>
                        <td>Expedita?</td>
                        <td>Ipsam!</td>
                        <td>Omnis!</td>
                        </tr>
                        <tr>
                        <td>Vitae.</td>
                        <td>Cumque.</td>
                        <td>Repudiandae.</td>
                        <td>Ut?</td>
                        <td>Sed!</td>
                        </tr>
                        <tr>
                        <td>Accusantium.</td>
                        <td>Adipisci.</td>
                        <td>Sit.</td>
                        <td>Maxime.</td>
                        <td>Harum.</td>
                        </tr>
                        <tr>
                        <td>Quas!</td>
                        <td>Velit.</td>
                        <td>Quisquam?</td>
                        <td>Rerum?</td>
                        <td>Iusto?</td>
                        </tr>
                        <tr>
                        <td>Voluptates!</td>
                        <td>Fugiat?</td>
                        <td>Alias.</td>
                        <td>Doloribus.</td>
                        <td>Veritatis.</td>
                        </tr>
                        <tr>
                        <td>Maiores.</td>
                        <td>Ab.</td>
                        <td>Accusantium.</td>
                        <td>Ullam!</td>
                        <td>Eveniet.</td>
                        </tr>
                        <tr>
                        <td>Hic.</td>
                        <td>Id!</td>
                        <td>Officiis.</td>
                        <td>Modi!</td>
                        <td>Obcaecati.</td>
                        </tr>
                        <tr>
                        <td>Soluta.</td>
                        <td>Ad!</td>
                        <td>Impedit.</td>
                        <td>Alias!</td>
                        <td>Ad.</td>
                        </tr>
                        <tr>
                        <td>Expedita.</td>
                        <td>Quo.</td>
                        <td>Exercitationem!</td>
                        <td>Optio?</td>
                        <td>Ipsum?</td>
                        </tr>
                        <tr>
                        <td>Commodi!</td>
                        <td>Rem.</td>
                        <td>Aspernatur.</td>
                        <td>Accusantium!</td>
                        <td>Maiores.</td>
                        </tr>
                        <tr>
                        <td>Omnis.</td>
                        <td>Cumque?</td>
                        <td>Eveniet!</td>
                        <td>Mollitia?</td>
                        <td>Vero.</td>
                        </tr>
                        <tr>
                        <td>Error!</td>
                        <td>Inventore.</td>
                        <td>Quasi!</td>
                        <td>Ducimus.</td>
                        <td>Repudiandae!</td>
                        </tr>
                        <tr>
                        <td>Dolores!</td>
                        <td>Necessitatibus.</td>
                        <td>Corrupti!</td>
                        <td>Eum.</td>
                        <td>Sunt!</td>
                        </tr>
                        <tr>
                        <td>Ea.</td>
                        <td>Culpa?</td>
                        <td>Quam?</td>
                        <td>Nemo!</td>
                        <td>Sit!</td>
                        </tr>
                        <tr>
                        <td>Veritatis!</td>
                        <td>Facilis.</td>
                        <td>Expedita?</td>
                        <td>Ipsam!</td>
                        <td>Omnis!</td>
                        </tr>
                        <tr>
                        <td>Vitae.</td>
                        <td>Cumque.</td>
                        <td>Repudiandae.</td>
                        <td>Ut?</td>
                        <td>Sed!</td>
                        </tr>
                        <tr>
                        <td>Accusantium.</td>
                        <td>Adipisci.</td>
                        <td>Sit.</td>
                        <td>Maxime.</td>
                        <td>Harum.</td>
                        </tr>
                        <tr>
                        <td>Quas!</td>
                        <td>Velit.</td>
                        <td>Quisquam?</td>
                        <td>Rerum?</td>
                        <td>Iusto?</td>
                        </tr>
                        <tr>
                        <td>Voluptates!</td>
                        <td>Fugiat?</td>
                        <td>Alias.</td>
                        <td>Doloribus.</td>
                        <td>Veritatis.</td>
                        </tr>
                        <tr>
                        <td>Maiores.</td>
                        <td>Ab.</td>
                        <td>Accusantium.</td>
                        <td>Ullam!</td>
                        <td>Eveniet.</td>
                        </tr>
                        <tr>
                        <td>Hic.</td>
                        <td>Id!</td>
                        <td>Officiis.</td>
                        <td>Modi!</td>
                        <td>Obcaecati.</td>
                        </tr>
                        <tr>
                        <td>Soluta.</td>
                        <td>Ad!</td>
                        <td>Impedit.</td>
                        <td>Alias!</td>
                        <td>Ad.</td>
                        </tr>
                        <tr>
                        <td>Expedita.</td>
                        <td>Quo.</td>
                        <td>Exercitationem!</td>
                        <td>Optio?</td>
                        <td>Ipsum?</td>
                        </tr>
                        <tr>
                        <td>Commodi!</td>
                        <td>Rem.</td>
                        <td>Aspernatur.</td>
                        <td>Accusantium!</td>
                        <td>Maiores.</td>
                        </tr>
                        <tr>
                        <td>Omnis.</td>
                        <td>Cumque?</td>
                        <td>Eveniet!</td>
                        <td>Mollitia?</td>
                        <td>Vero.</td>
                        </tr>
                        <tr>
                        <td>Error!</td>
                        <td>Inventore.</td>
                        <td>Quasi!</td>
                        <td>Ducimus.</td>
                        <td>Repudiandae!</td>
                        </tr>
                        <tr>
                        <td>Dolores!</td>
                        <td>Necessitatibus.</td>
                        <td>Corrupti!</td>
                        <td>Eum.</td>
                        <td>Sunt!</td>
                        </tr>
                        <tr>
                        <td>Ea.</td>
                        <td>Culpa?</td>
                        <td>Quam?</td>
                        <td>Nemo!</td>
                        <td>Sit!</td>
                        </tr>
                        <tr>
                        <td>Veritatis!</td>
                        <td>Facilis.</td>
                        <td>Expedita?</td>
                        <td>Ipsam!</td>
                        <td>Omnis!</td>
                        </tr>
                        <tr>
                        <td>Vitae.</td>
                        <td>Cumque.</td>
                        <td>Repudiandae.</td>
                        <td>Ut?</td>
                        <td>Sed!</td>
                        </tr>
                        <tr>
                        <td>Accusantium.</td>
                        <td>Adipisci.</td>
                        <td>Sit.</td>
                        <td>Maxime.</td>
                        <td>Harum.</td>
                        </tr>
                        <tr>
                        <td>Quas!</td>
                        <td>Velit.</td>
                        <td>Quisquam?</td>
                        <td>Rerum?</td>
                        <td>Iusto?</td>
                        </tr>
                        <tr>
                        <td>Voluptates!</td>
                        <td>Fugiat?</td>
                        <td>Alias.</td>
                        <td>Doloribus.</td>
                        <td>Veritatis.</td>
                        </tr>
                        <tr>
                        <td>Maiores.</td>
                        <td>Ab.</td>
                        <td>Accusantium.</td>
                        <td>Ullam!</td>
                        <td>Eveniet.</td>
                        </tr>
                        <tr>
                        <td>Hic.</td>
                        <td>Id!</td>
                        <td>Officiis.</td>
                        <td>Modi!</td>
                        <td>Obcaecati.</td>
                        </tr>
                        <tr>
                        <td>Soluta.</td>
                        <td>Ad!</td>
                        <td>Impedit.</td>
                        <td>Alias!</td>
                        <td>Ad.</td>
                        </tr>
                        <tr>
                        <td>Expedita.</td>
                        <td>Quo.</td>
                        <td>Exercitationem!</td>
                        <td>Optio?</td>
                        <td>Ipsum?</td>
                        </tr>
                        <tr>
                        <td>Commodi!</td>
                        <td>Rem.</td>
                        <td>Aspernatur.</td>
                        <td>Accusantium!</td>
                        <td>Maiores.</td>
                        </tr>
                        <tr>
                        <td>Omnis.</td>
                        <td>Cumque?</td>
                        <td>Eveniet!</td>
                        <td>Mollitia?</td>
                        <td>Vero.</td>
                        </tr>
                        <tr>
                        <td>Error!</td>
                        <td>Inventore.</td>
                        <td>Quasi!</td>
                        <td>Ducimus.</td>
                        <td>Repudiandae!</td>
                        </tr>
                        <tr>
                        <td>Dolores!</td>
                        <td>Necessitatibus.</td>
                        <td>Corrupti!</td>
                        <td>Eum.</td>
                        <td>Sunt!</td>
                        </tr>
                        <tr>
                        <td>Ea.</td>
                        <td>Culpa?</td>
                        <td>Quam?</td>
                        <td>Nemo!</td>
                        <td>Sit!</td>
                        </tr>
                        <tr>
                        <td>Veritatis!</td>
                        <td>Facilis.</td>
                        <td>Expedita?</td>
                        <td>Ipsam!</td>
                        <td>Omnis!</td>
                        </tr>
                        <tr>
                        <td>Vitae.</td>
                        <td>Cumque.</td>
                        <td>Repudiandae.</td>
                        <td>Ut?</td>
                        <td>Sed!</td>
                        </tr>
                        <tr>
                        <td>Accusantium.</td>
                        <td>Adipisci.</td>
                        <td>Sit.</td>
                        <td>Maxime.</td>
                        <td>Harum.</td>
                        </tr>
                    </tbody>
                    </table>
            </div>
        );
    }
    else {
        return (<Redirect to="/" />)
    }
}

export default List;
